In [5]:
import numpy as np

In [15]:
PM10=np.random.normal(19,5,1000)
PM10

array([17.3648583 , 16.62900651, 17.29922472, 26.17248735, 18.47654523,
       15.55613761, 14.2431689 , 17.33914642, 17.69653123, 19.23398825,
       12.50185181, 16.21420987, 27.55785711, 20.91906039, 12.29607013,
       29.02646123, 15.35154204, 12.85931652, 19.6581107 , 18.14860522,
       18.21061668, 20.29668731, 18.83977491, 23.78817493, 19.23919892,
       20.39581468, 17.490826  , 23.43007638, 17.17682982, 17.45952536,
       12.4592932 , 10.92084771, 15.98135434,  6.24104397, 17.62223909,
       18.57683984, 23.7255745 , 21.16543487, 18.66439342, 16.38612616,
       15.78744118, 21.47514813, 22.52756466, 23.01027304, 16.93684404,
       21.09759194,  7.45773014, 22.79345396, 25.05214512, 17.87554819,
       28.81511067, 34.95646238, 19.26422115, 19.11370964, 16.18503371,
       19.32966484, 15.21192372, 23.27834488, 13.34209928, 23.18899794,
       12.81431626, 16.17892798, 29.06240832, 17.50312812, 24.13736335,
       18.96957746, 12.41742461, 21.08439459, 22.43247175, 27.19

In [16]:
indici=np.random.randint(0,1001,20)
PM10[indici]=9999.9
PM10

array([1.73648583e+01, 1.66290065e+01, 1.72992247e+01, 2.61724874e+01,
       1.84765452e+01, 1.55561376e+01, 1.42431689e+01, 1.73391464e+01,
       1.76965312e+01, 1.92339882e+01, 1.25018518e+01, 1.62142099e+01,
       2.75578571e+01, 2.09190604e+01, 9.99990000e+03, 2.90264612e+01,
       1.53515420e+01, 1.28593165e+01, 1.96581107e+01, 1.81486052e+01,
       1.82106167e+01, 2.02966873e+01, 1.88397749e+01, 2.37881749e+01,
       1.92391989e+01, 2.03958147e+01, 1.74908260e+01, 2.34300764e+01,
       1.71768298e+01, 1.74595254e+01, 1.24592932e+01, 1.09208477e+01,
       1.59813543e+01, 6.24104397e+00, 1.76222391e+01, 1.85768398e+01,
       2.37255745e+01, 2.11654349e+01, 1.86643934e+01, 1.63861262e+01,
       1.57874412e+01, 2.14751481e+01, 2.25275647e+01, 2.30102730e+01,
       9.99990000e+03, 2.10975919e+01, 7.45773014e+00, 2.27934540e+01,
       2.50521451e+01, 1.78755482e+01, 2.88151107e+01, 3.49564624e+01,
       1.92642212e+01, 1.91137096e+01, 1.61850337e+01, 1.93296648e+01,
      

In [22]:
Z=np.arange(1,15)
Z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
R=np.array([Z[i:i+4] for i in range(0,11)])
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])