
# Esercizio 4
1000 classi da 25 alunni ciscuna
ogni possibile data di nascita è un numero da 1 a 365


In [1]:
import numpy as np

In [34]:
n_alunni=30
classe=np.random.randint(1,365,(1000,n_alunni))
classe

array([[ 18, 210, 343, ..., 162, 118, 305],
       [313, 340, 154, ..., 147, 135, 182],
       [327, 363, 200, ...,  58, 252, 301],
       ...,
       [263,   4, 233, ..., 257,  46, 354],
       [ 28,  42,  22, ...,  55,  74, 321],
       [243, 346, 218, ..., 303, 225,  39]])

In [35]:
np.unique(classe,axis=0)

array([[  1, 149, 280, ..., 225, 141, 288],
       [  1, 336, 200, ..., 338, 141, 261],
       [  1, 358, 119, ..., 143,  48, 340],
       ...,
       [363,  24, 343, ...,  97, 329, 212],
       [363, 105, 111, ..., 210, 326,  76],
       [364,  55, 221, ..., 190, 302,  99]])

In [36]:
classi_con_almeno_doppione=0
for c in classe:
    if np.unique(c).shape[0]<n_alunni:
        classi_con_almeno_doppione=classi_con_almeno_doppione+1
classi_con_almeno_doppione

720

# Esercizio 3

In [73]:
n_lanci=1000
partite=np.random.choice((0,1),(10000,n_lanci))
print(partite)

[[0 0 0 ... 1 0 0]
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 1 0 1]
 ...
 [0 0 1 ... 1 1 1]
 [1 0 1 ... 1 0 1]
 [0 0 0 ... 0 0 0]]


In [74]:
cont=0
for p in partite:
    if np.count_nonzero(p)<450:
        lanci_croce+=1
        
lanci_croce
        

5000998