In [1]:
import numpy as np

In [40]:
l=300
array=np.random.randint(0,10,l)
array

array([6, 1, 3, 0, 5, 6, 5, 0, 7, 7, 8, 6, 9, 6, 5, 0, 1, 5, 5, 1, 8, 2,
       5, 7, 2, 9, 8, 4, 7, 3, 8, 2, 3, 3, 4, 9, 6, 1, 8, 0, 7, 0, 8, 4,
       9, 0, 4, 9, 4, 9, 6, 4, 3, 7, 5, 3, 0, 0, 4, 7, 0, 7, 4, 7, 0, 0,
       5, 9, 8, 2, 1, 4, 9, 1, 4, 0, 5, 4, 5, 7, 2, 2, 1, 7, 3, 1, 9, 7,
       0, 3, 0, 5, 9, 9, 2, 6, 7, 3, 5, 1, 5, 5, 3, 2, 0, 2, 9, 7, 4, 0,
       5, 8, 1, 7, 7, 7, 9, 0, 0, 8, 0, 6, 3, 3, 8, 1, 4, 5, 9, 6, 8, 5,
       4, 9, 6, 2, 2, 7, 6, 8, 2, 9, 0, 9, 7, 6, 7, 0, 7, 4, 0, 4, 7, 5,
       0, 9, 1, 4, 4, 8, 5, 4, 6, 8, 5, 0, 0, 5, 4, 6, 1, 4, 9, 1, 1, 4,
       1, 5, 3, 2, 3, 1, 8, 2, 9, 0, 3, 1, 5, 8, 1, 1, 4, 9, 3, 2, 7, 9,
       8, 7, 3, 4, 7, 2, 4, 5, 0, 2, 7, 6, 7, 7, 0, 6, 5, 7, 5, 1, 6, 9,
       4, 4, 3, 1, 7, 2, 4, 1, 1, 2, 6, 4, 1, 3, 5, 6, 3, 2, 6, 4, 1, 6,
       1, 7, 9, 0, 3, 7, 3, 2, 2, 2, 7, 3, 6, 6, 8, 5, 2, 1, 7, 5, 6, 7,
       5, 7, 6, 2, 5, 8, 2, 9, 5, 6, 2, 4, 3, 8, 5, 0, 8, 0, 0, 4, 0, 6,
       2, 2, 4, 0, 0, 4, 8, 3, 4, 9, 9, 6, 0, 5])

In [41]:
array_pos=np.arange(0,l)

array([False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False,  True, False, False, False, False, False, False, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,

In [42]:
np.roll(array,-1)==2

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [43]:
sequanza_123=np.logical_and(np.logical_and(array == 1,np.roll(array,-1)==2),np.roll(array,-2)==3)
sequanza_123

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [45]:
array_pos[sequanza_123]

array([], dtype=int64)