In [1]:
import numpy as np

In [2]:
lista=[1,2,3,4]

In [3]:
type(lista)

list

In [4]:
array=np.array(lista)
array

array([1, 2, 3, 4])

In [5]:
type(array)

numpy.ndarray

In [6]:
3*array

array([ 3,  6,  9, 12])

In [7]:
3*lista

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
10+array

array([11, 12, 13, 14])

In [9]:
array

array([1, 2, 3, 4])

In [10]:
a=array.copy()
a

array([1, 2, 3, 4])

In [11]:
b=np.array(lista[::-1])
b

array([4, 3, 2, 1])

In [12]:
a+b

array([5, 5, 5, 5])

In [13]:
zeri=np.zeros(10,dtype=np.int8)
zeri

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [14]:
uni=np.ones(10,dtype=np.int8)
uni

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [15]:
np.random.uniform(size=10)

array([0.76646187, 0.51490508, 0.31546814, 0.58409613, 0.87680293,
       0.60335387, 0.77874277, 0.99943394, 0.46336239, 0.71244373])

In [16]:
alice=np.random.randint(1,7,10)
alice

array([5, 6, 3, 6, 4, 5, 6, 2, 6, 2])

In [17]:
bob=np.random.randint(1,7,10)
bob

array([3, 4, 4, 5, 2, 4, 4, 1, 3, 2])

In [18]:
alicevince=alice>bob
print(alicevince)
alicevince.dtype

[ True  True False  True  True  True  True  True  True False]


dtype('bool')

In [19]:
alice.dtype

dtype('int64')

## indicizzazione booleana

In [20]:
alice[alicevince]

array([5, 6, 6, 4, 5, 6, 2, 6])

In [21]:
bob[alicevince]

array([3, 4, 5, 2, 4, 4, 1, 3])

## intervalli di numeri interi

In [22]:
np.arange(3,22,3)

array([ 3,  6,  9, 12, 15, 18, 21])

## Intervalli di numeri reali

In [23]:
np.linspace(0.0,5.0,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

## Numeri casuali

In [24]:
np.random.uniform(0.,10.,5)

array([4.31645868, 7.72285326, 5.13526551, 0.73064061, 4.45176063])

In [25]:
np.random.randint(1,7,5)

array([3, 2, 1, 1, 2])

In [26]:
print(np.random.choice(["Testa","Croce"],10000000))

['Testa' 'Croce' 'Croce' ... 'Croce' 'Croce' 'Croce']


E={T,C} 

Pe=Ne/Nt, numero di volte che e capitato diviso il nuemro di volte dell'evento(definizione frequentista)

Nt=100, Ne=51, Pe=51/100=0,51

In [27]:
np.random.choice(["Testa","croce"],10,p=[0.7,0.3])

array(['croce', 'Testa', 'Testa', 'Testa', 'Testa', 'Testa', 'Testa',
       'Testa', 'croce', 'croce'], dtype='<U5')

In [28]:
np.random.choice([2],10)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## CURVA GAUSSIANA

In [29]:
altezze=np.random.normal(178,10,(5,7))
altezze

array([[193.62381579, 186.69208656, 195.19797038, 168.23574943,
        162.38994366, 178.49820427, 184.04150957],
       [177.27222959, 161.82867629, 193.36187257, 164.07581711,
        174.14258808, 178.78358672, 184.55885392],
       [173.22942923, 174.27163288, 189.04048618, 175.33889627,
        169.26586574, 190.70770672, 184.70685421],
       [170.46382364, 186.66893648, 165.07419282, 173.72327017,
        168.27015783, 158.45130142, 162.97296684],
       [159.5481491 , 191.83516708, 170.46813797, 188.9125176 ,
        152.38017174, 185.2047694 , 158.33529722]])

In [30]:
np.max(altezze)

195.1979703824854

In [31]:
np.min(altezze)

152.3801717397169

In [32]:
array_2d=np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
array_2d.shape

(2, 3)

In [34]:
array_2d_casuale=np.random.uniform(0,1,(8,2))
array_2d_casuale

array([[9.12368088e-01, 5.06305720e-01],
       [2.57445157e-01, 7.78916215e-01],
       [6.49602255e-01, 4.32876528e-01],
       [3.37550591e-01, 6.63252822e-02],
       [6.42694909e-01, 3.36517386e-02],
       [9.05609026e-04, 9.55773533e-02],
       [1.17914957e-01, 2.19346476e-01],
       [5.55027803e-01, 2.39696821e-01]])

### elemento

In [35]:
array_2d_casuale[3,1]

0.06632528219449241

### colonna

In [36]:
array_2d_casuale[:,0]

array([9.12368088e-01, 2.57445157e-01, 6.49602255e-01, 3.37550591e-01,
       6.42694909e-01, 9.05609026e-04, 1.17914957e-01, 5.55027803e-01])

### Riga

In [37]:
array_2d_casuale[3,:]

array([0.33755059, 0.06632528])

### Blocco

In [38]:
array_2d_casuale[2:5,:]

array([[0.64960225, 0.43287653],
       [0.33755059, 0.06632528],
       [0.64269491, 0.03365174]])

### Assegnazione

In [39]:
array_2d_casuale[2:5,:]=1.
array_2d_casuale

array([[9.12368088e-01, 5.06305720e-01],
       [2.57445157e-01, 7.78916215e-01],
       [1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00],
       [9.05609026e-04, 9.55773533e-02],
       [1.17914957e-01, 2.19346476e-01],
       [5.55027803e-01, 2.39696821e-01]])

# ESERCIZIO

## Soluzione numpy

In [40]:
n = 1000000

In [41]:
%%timeit
array=np.zeros(n,dtype=np.int8)
array[::2]=1.

461 µs ± 18.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Soluzione python

In [42]:
%%timeit
l=[i%2 for i in range(n)]
l

80.4 ms ± 2.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [43]:
array_1d=np.arange(1,20)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [44]:
array_1d[::5]=-1
array_1d

array([-1,  2,  3,  4,  5, -1,  7,  8,  9, 10, -1, 12, 13, 14, 15, -1, 17,
       18, 19])

In [45]:
array_1d=np.arange(0,5)
array_1d

array([0, 1, 2, 3, 4])

In [46]:
resto_fa_zero=array_1d%2==0

In [47]:
array_1d[resto_fa_zero]

array([0, 2, 4])

In [48]:
array_1d[resto_fa_zero]=999
array_1d

array([999,   1, 999,   3, 999])

In [49]:
array_1d=np.random.uniform(0.,1.,10)
array_1d

array([0.53379715, 0.2571858 , 0.08601193, 0.45916206, 0.50282912,
       0.1662475 , 0.13604005, 0.49703807, 0.97900677, 0.1303771 ])

In [50]:
array_1d[np.array([1,2,9])]=999 #indicizzazione con array di indici

In [51]:
array_1d

array([5.33797155e-01, 9.99000000e+02, 9.99000000e+02, 4.59162062e-01,
       5.02829118e-01, 1.66247503e-01, 1.36040049e-01, 4.97038070e-01,
       9.79006765e-01, 9.99000000e+02])

# LEZIONE 2/11/22


## IL BROADCAST

In [53]:
array1=np.array([1,2,3,4,5])
array1*5

array([ 5, 10, 15, 20, 25])

In [54]:
np.exp(array1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [55]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [56]:
array1+10

array([11, 12, 13, 14, 15])

In [60]:
array2=np.array([-1,-2,-3,-4,-5,-6])
array2

array([-1, -2, -3, -4, -5, -6])

In [61]:
array1+array2

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [66]:
matrice1=np.ones((5,5))
matrice1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [72]:
matrice2=np.random.uniform(0,1,(5,1))
matrice2

array([[0.83093799],
       [0.31556634],
       [0.28795108],
       [0.05650308],
       [0.05882972]])

In [73]:
matrice1+matrice2

array([[1.83093799, 1.83093799, 1.83093799, 1.83093799, 1.83093799],
       [1.31556634, 1.31556634, 1.31556634, 1.31556634, 1.31556634],
       [1.28795108, 1.28795108, 1.28795108, 1.28795108, 1.28795108],
       [1.05650308, 1.05650308, 1.05650308, 1.05650308, 1.05650308],
       [1.05882972, 1.05882972, 1.05882972, 1.05882972, 1.05882972]])

In [75]:
matrice_5=4+np.ones((5,5))
matrice_5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])