In [1]:
import numpy as np

In [2]:
partite_alice=np.random.choice((0,0.5,1),(10,1000))
partite_bob=np.random.choice((0,0.5,1),(10,1000))
print(partite_bob)
print(partite_alice)

[[0.5 0.5 1.  ... 1.  0.  0.5]
 [0.  0.  1.  ... 0.  0.5 0.5]
 [0.  0.5 1.  ... 1.  0.5 0. ]
 ...
 [0.5 0.5 0.  ... 0.  0.  0.5]
 [0.5 0.  0.  ... 0.5 1.  0. ]
 [0.5 0.  0.  ... 1.  0.  1. ]]
[[0.5 1.  0.5 ... 0.5 1.  0.5]
 [0.  0.  0.  ... 1.  0.5 0.5]
 [0.5 0.  0.5 ... 0.  1.  0.5]
 ...
 [0.5 0.5 1.  ... 1.  0.  0.5]
 [0.  0.  0.5 ... 0.5 0.5 0.5]
 [0.  1.  0.  ... 0.  1.  1. ]]


In [3]:
punti_bob=[]
for elemento in partite_bob:
    punti_bob.append(sum(elemento))
punti_bob

[498.5, 498.0, 488.0, 527.0, 501.5, 470.0, 482.0, 492.5, 513.0, 523.0]

In [4]:
punti_alice=[]
for elemento in partite_alice:
    punti_alice.append(sum(elemento))
punti_alice

[518.5, 521.5, 491.5, 500.0, 500.0, 478.0, 487.0, 511.5, 509.5, 490.5]

In [5]:
punti_bob=np.array(punti_bob)
punti_alice=np.array(punti_alice)
risultati=punti_alice>punti_bob
risultati

array([ True,  True,  True, False, False,  True,  True,  True, False,
       False])

In [6]:
vincite_alice=np.count_nonzero(risultati)
print(f"alice ha vinto {vincite_alice} volte in 10 partite, e ne ha perse {len(risultati)-vincite_alice}")
print(f"bob ha vinto {len(risultati)-vincite_alice} volte in 10 partite, e ne ha perse {vincite_alice}")

alice ha vinto 6 volte in 10 partite, e ne ha perse 4
bob ha vinto 4 volte in 10 partite, e ne ha perse 6


In [9]:
#Soluzione in classe
for i in range(0,10):
    g1=np.random.randint(1,7,1000)
    g2=np.random.randint(1,7,1000)
    
    pari=np.count_nonzero(g1==g2)
    a2=np.count_nonzero(g2>g1)+pari/2
    a1=np.count_nonzero(g1>g2)+pari/2
    print(a1,a2)
    


482.0 518.0
511.5 488.5
523.0 477.0
499.5 500.5
516.0 484.0
508.5 491.5
497.0 503.0
491.0 509.0
504.5 495.5
510.5 489.5


In [12]:
#Soluzione in classe
for i in range(0,30):
    g1=np.random.randint(1,7,1000)
    g2=np.random.choice([1,2,3,4,5,6],p=[1/8,1/8,1/8,1/8,1/4,1/4])
    
    pari=np.count_nonzero(g1==g2)
    a2=np.count_nonzero(g2>g1)+pari/2
    a1=np.count_nonzero(g1>g2)+pari/2
    print(a1,a2)
    

241.5 758.5
225.0 775.0
257.5 742.5
246.0 754.0
599.5 400.5
565.0 435.0
415.5 584.5
254.0 746.0
776.5 223.5
90.0 910.0
751.5 248.5
261.0 739.0
404.0 596.0
918.0 82.0
257.0 743.0
247.5 752.5
757.5 242.5
269.5 730.5
74.5 925.5
751.5 248.5
254.0 746.0
265.5 734.5
571.5 428.5
911.0 89.0
228.0 772.0
261.5 738.5
916.5 83.5
87.0 913.0
259.5 740.5
279.0 721.0
