# COGNOME NOME

In [17]:
import numpy as np

# Esercizio 1
Creare un notebook jupyter che a partire dal testo contenuto nel file ___"J_Verne_girodelmondoin80giorni.txt"___:

1. crei un dizionario delle frequenze per ciascun carattere (**line feed escluso**); 
2. crei il dizionario delle adiacenze per ciascun carattere (**line feed escluso**);
3. **[FACOLTATIVO]** crei un indice dei capitoli. Ogni capitolo inizia riportando il numero romano del capitolo e il suo titolo in questo modo:

>CAPITOLO XXIX.
>
>Nel quale si narrano cose che capitano unicamente sulle ferrovie
>americane.

In [69]:
file=open( "J_Verne_girodelmondoin80giorni.txt","r")
linee=file.readlines()
linee_div=[]
linee_div_tot=[]
for elemento in linee:

    linee_div.append(elemento.split())
    
for elemento,i in linee_div:
    linee_div_tot.append(elemento[i].split())
linee_div_tot
 

TypeError: 'int' object is not subscriptable

# Esercizio 2
Dato `n`numero intero maggiore o uguale a 2 crea una matrice di numpy che abbia la struttura seguente esemplificata, per il caso `n=7`. 

`[[1 2 1 2 1 2 1]
 [ 2 1 2 1 2 1 2]
 [ 1 2 1 2 1 2 1]
 [ 2 1 2 1 2 1 2]
 [ 1 2 1 2 1 2 1]
 [ 2 1 2 1 2 1 2]
 [ 1 2 1 2 1 2 1]]`
 

In [27]:
n=7

array=np.ones((n,n),dtype=np.int16)
for i in range(0,len(array)):
    if i%2==0:
        array[i,1::2]=2
    else:
        array[i,::2]=2
array

array([[1, 2, 1, 2, 1, 2, 1],
       [2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1],
       [2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1],
       [2, 1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2, 1]], dtype=int16)

# Esercizio 3
Crea un array unidimensionale di numpy lungo 21 elementi i cui valori sono 1,2 e 3 alernatici ciclicamente (`[1,2,3,1,2,3,.....]`).

In [65]:
array=np.ones(21,dtype=np.int16)
array[1::3]=2
array[2::3]=3
array

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
      dtype=int16)